from .._shared.field_types import B, I, J, S, T

TABLE = "clients"
FIELDS = {
    "client_type": S,
    "individual_type": S,
    "business_type": S,
    "legal_name": (S, {"nullable": False}),
    "operating_name": S,
    "industry": S,
    "preferred_office": S,
    "preferred_contact_method": S,
    "lead_source": S,
    "referral_source": S,
    "urgency_level": (S, {"default": "This Month"}),
    "desired_start_date": S,
    "primary_contact_name": S,
    "contact_person_position": S,
    "contact_person_email": S,
    "contact_person_phone": S,
    "contact_person_address": S,
    "primary_email": (S, {"nullable": False}),
    "primary_phone": S,
    "website": S,
    "address": S,
    "city": S,
    "province": S,
    "postal_code": S,
    "business_number": S,
    "gst_hst_number": S,
    "pst_number": S,
    "payroll_number": S,
    "corp_number_federal": S,
    "corp_number_provincial": S,
    "number_of_shareholders": S,
    "incorporation_date": S,
    "fiscal_year_end": S,
    "number_of_employees": I,
    "last_year_revenue": S,
    "annual_revenue": S,
    "services_needed": J,
    "current_accounting_software": S,
    "previous_accountant": S,
    "outstanding_issues": T,
    "special_requirements": T,
    "status": (S, {"default": "Onboarding"}),
    "assigned_to": S,
    "client_value_tier": (S, {"default": "New"}),
    "payment_terms": (S, {"default": "Net 30"}),
    "active_package": S,
    "package_price": S,
    "package_billing": S,
    "safe_isc_user_id": S,
    "safe_isc_password": S,
    "safe_isc_web_code": S,
    "safe_inc_canada_user_id": S,
    "safe_inc_canada_password": S,
    "safe_inc_canada_web_code": S,
    "safe_pst_id": S,
    "safe_pst_password": S,
    "safe_cra_id": S,
    "safe_cra_password": S,
    "notes": T,
}
REQUIRED = ["client_type", "legal_name", "primary_email"]
EXCLUDED = set()
