import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const payload = await req.json();
    
    const { event, data } = payload;
    
    // Only process if document has a service_filing_id
    if (!data.service_filing_id) {
      return Response.json({ 
        message: 'No service filing linked, skipping task generation',
        status: 'skipped' 
      });
    }
    
    // Get the service filing
    const filing = await base44.asServiceRole.entities.ServiceFiling.get(data.service_filing_id);
    
    if (!filing) {
      return Response.json({ 
        error: 'Service filing not found',
        status: 'error' 
      });
    }
    
    // Get client info
    const client = await base44.asServiceRole.entities.Client.get(data.client_id);
    
    // Determine assigned staff
    let assignedStaff = filing.assigned_to || client?.assigned_to;
    
    if (!assignedStaff) {
      const admins = await base44.asServiceRole.entities.User.filter({ role: 'admin' });
      assignedStaff = admins[0]?.email;
    }
    
    // Update filing status if it was "Documents Pending"
    if (filing.status === 'Documents Pending') {
      await base44.asServiceRole.entities.ServiceFiling.update(filing.id, {
        status: 'In Progress'
      });
    }
    
    // Send task notification to assigned staff
    if (assignedStaff) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        from_name: 'GoGet CRM - Tax Filing System',
        to: assignedStaff,
        subject: `🎯 New Task: Process Document for ${filing.service_name}`,
        body: `A new document has arrived for processing.

Client: ${client?.legal_name || 'Unknown'}
Service Filing: ${filing.service_name} (${filing.filing_year})
Due Date: ${filing.due_date ? new Date(filing.due_date).toLocaleDateString() : 'Not set'}

Document Details:
- Name: ${data.document_name}
- Type: ${data.document_type}
- Tax Year: ${data.tax_year || filing.filing_year}
- Upload Date: ${new Date(data.created_date).toLocaleDateString()}

Filing Status: ${filing.status} → ${filing.status === 'Documents Pending' ? 'In Progress (Auto-updated)' : filing.status}

Action Required:
1. Review the uploaded document
2. Verify completeness
3. Update filing status as work progresses
4. Contact client if additional documents needed

View Document: ${data.file_url}

This task was automatically generated by the GoGet filing workflow engine.`
      });
    }
    
    return Response.json({ 
      success: true,
      message: 'Task created and filing status updated',
      assigned_to: assignedStaff,
      filing: filing.service_name,
      status_updated: filing.status === 'Documents Pending',
      new_status: filing.status === 'Documents Pending' ? 'In Progress' : filing.status
    });
    
  } catch (error) {
    console.error('Workflow error:', error);
    return Response.json({ 
      error: error.message,
      status: 'error' 
    }, { status: 500 });
  }
});