import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const payload = await req.json();
    
    const { event, data } = payload;
    
    // Get the document that was signed
    const document = await base44.asServiceRole.entities.Document.get(data.document_id);
    
    if (!document) {
      return Response.json({ 
        error: 'Document not found',
        status: 'error' 
      });
    }
    
    // Get client info
    const client = await base44.asServiceRole.entities.Client.get(data.client_id);
    
    // Get assigned staff member
    let assignedStaff = client?.assigned_to;
    
    if (data.service_filing_id) {
      const filing = await base44.asServiceRole.entities.ServiceFiling.get(data.service_filing_id);
      assignedStaff = filing?.assigned_to || assignedStaff;
    }
    
    if (!assignedStaff) {
      const admins = await base44.asServiceRole.entities.User.filter({ role: 'admin' });
      assignedStaff = admins[0]?.email;
    }
    
    // Notify staff that document was signed
    if (assignedStaff) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        from_name: 'GoGet CRM - Document System',
        to: assignedStaff,
        subject: `✍️ Document Signed: ${document.document_name}`,
        body: `A document has been electronically signed by the client.

Client: ${client?.legal_name || 'Unknown'}
Signer: ${data.signer_name}
Email: ${data.signer_email}

Document Details:
- Name: ${document.document_name}
- Type: ${data.document_type}
- Signed Date: ${new Date(data.signed_date).toLocaleString()}

The document status has been automatically updated to "Processed" and marked as verified.

${data.service_filing_id ? 'Associated service filing status has been updated if applicable.' : ''}

Action: Review the signed document and proceed with filing/processing.

This notification was automatically generated by the GoGet signature workflow.`
      });
    }
    
    // Send confirmation email to client
    if (client?.primary_email) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        from_name: 'GoGet Accounting',
        to: client.primary_email,
        subject: `✅ Signature Confirmation: ${document.document_name}`,
        body: `Dear ${data.signer_name},

This confirms that you have successfully signed the following document electronically:

Document: ${document.document_name}
Type: ${data.document_type}
Signed On: ${new Date(data.signed_date).toLocaleString()}

Your electronic signature has been securely recorded and has the same legal effect as a handwritten signature.

A copy of your signature confirmation is available in your client portal.

Thank you for using our digital signature service.

GoGet Accounting Team`
      });
    }
    
    return Response.json({ 
      success: true,
      message: 'Document signed notification sent',
      document: document.document_name,
      signer: data.signer_name,
      staff_notified: assignedStaff,
      client_notified: client?.primary_email
    });
    
  } catch (error) {
    console.error('Workflow error:', error);
    return Response.json({ 
      error: error.message,
      status: 'error' 
    }, { status: 500 });
  }
});