"""add communication author_email sender_type

Revision ID: 185d1a4300e4
Revises: 0c1411ced05c
Create Date: 2026-07-27 08:02:26.138806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185d1a4300e4'
down_revision: Union[str, None] = '0c1411ced05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('author_email', sa.String(), nullable=True))
    op.add_column('communications', sa.Column('sender_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communications', 'sender_type')
    op.drop_column('communications', 'author_email')
    # ### end Alembic commands ###
