"""add signature client_id

Revision ID: ce266a5145f0
Revises: 185d1a4300e4
Create Date: 2026-07-27 08:22:51.694968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce266a5145f0'
down_revision: Union[str, None] = '185d1a4300e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signatures', sa.Column('client_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_signatures_client_id'), 'signatures', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_client_id'), table_name='signatures')
    op.drop_column('signatures', 'client_id')
    # ### end Alembic commands ###
